# Supply-chain checks via cargo-deny: advisories, licenses, banned crates, sources.
# Complements audit.yml (which opens issues on a schedule) with license/ban/source
# enforcement on every dependency change.
name: cargo-deny

on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
      - ".github/workflows/deny.yml"
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: deny-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-deny:
    name: cargo deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check advisories bans sources licenses
